#!/bin/bash

#####################################################################################
#
# Test our code against various unit test systems and linters and prevent commit
# if any of them fail.
#
# @version 6.2.0
#
# Adjusted for use with this specific project.
# - Removed the `THEME` variable and replaced it with `PLUGIN_PATH` and `THEME_PATH`
# - Changed css_lint to use `stylelint` instead of `lipemat-css-boilerplate`
#
####################################################################################

PHP_VERSION="7.2"
PHPUNIT_DIR="dev/wp-unit"
WP_CONTENT="wp-content"

PLUGIN_PATH="";
THEME_PATH=""
#####################################################################################

GREEN="$(tput setaf 2)"
WHITE="$(tput setaf 7)"
YELLOW="$(tput setaf 3)"
RED="$(tput setaf 1)"
BLUE="$(tput setaf 6)"
RESET_COLOR="$(tput sgr0)"

# Point to specific version of PHP if supported via environmental variables.
if [[ "true" == "$PHP_MULTI_VERSION_SUPPORT" ]]; then
    PHP="php ${PHP_VERSION}"
    PHPCS="phpcs ${PHP_VERSION}"
    PHPSTAN="phpstan ${PHP_VERSION}"
    PHPUNIT="phpunit ${PHP_VERSION}"
else
    PHP='php'
    PHPCS='phpcs'
    PHPSTAN='phpstan'
    PHPUNIT='phpunit'
fi
PROJECT=$(${PHP} -r "echo dirname(realpath('$0'), 3);")
## Fix windows paths
PROJECT=${PROJECT//\\//}

PHP_FILES=$(git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep "${THEME_PATH}/.*\
.php$\|${PLUGIN_PATH}/.*\.php$")

if [[ ! "$PHP_FILES" ]]; then
    echo "${YELLOW}[pre-commit]${BLUE} No Lintable PHP Files Changed ${RESET_COLOR}"
fi

# Pass the exit code to change the default exit code of 1 to something else.
function exit_reset_colors() {
    echo ${RESET_COLOR}
    exit ${1:-1}
}

function php_unit() {
    if [[ ! -f ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml ]] && [[ ! -f ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml.dist ]]; then
        echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml or ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml.dist not found!"
        exit_reset_colors
    fi
    echo "${YELLOW}[pre-commit]${BLUE} Running PHP Unit... ${WHITE}"
    cd "${PROJECT}/${PHPUNIT_DIR}" || exit
    OUTPUT=$(${PHPUNIT})
    if [[ $? != 0 ]]; then
        echo
        echo "${BLUE}PHP Unit Failed! Fix the error before commit!"
        echo "${RED}$OUTPUT"
        exit_reset_colors
    fi
    echo "${YELLOW}[pre-commit]${GREEN} PHP Unit Tests Passed!${RESET_COLOR}"
}
php_unit &

function php_lint() {
    if [[ "$PHP_FILES" ]]; then
        echo "${YELLOW}[pre-commit]${BLUE} Checking PHP Lint... ${WHITE}"
        for FILE in ${PHP_FILES}; do
            OUTPUT=$(${PHP} -l -d display_errors=0 ${PROJECT}/${FILE})
            if [[ $? != 0 ]]; then
                echo
                echo "${BLUE}PHP Lint Failed. Fix the error before commit."
                echo "${RED}$OUTPUT"
                exit_reset_colors
            fi
        done
        echo "${YELLOW}[pre-commit]${GREEN} PHP Lint Passed!${RESET_COLOR}"
    fi
}
php_lint &


# Go through each background task
# If it sent exit code 1, it failed and the result from `wait` will be false.
FAIL=0
for job in $(jobs -p); do
    wait "$job" || (( FAIL+=1 ))
done

echo "${RESET_COLOR}"

# If any of the background tasks failed, we exit 1
if [[ $FAIL -ne 0 ]]; then
    exit 1
else
    exit 0
fi
